apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: wasm
spec:
  type: bindings.wasm
  version: v1
  metadata:
    - name: url
      value: "file://components/dapr-wasm-binding/target/wasm32-wasi/release/dapr-wasm-binding.wasm"
