FROM rust:1.75 as builder
WORKDIR /usr/src/secrets-crypt
COPY secrets-crypt/ .
RUN cargo build --release

FROM debian:stable-slim

RUN apt-get update
RUN apt-get install -y openssl

COPY --from=builder /usr/src/secrets-crypt/target/release/secrets-crypt /usr/local/bin/secrets-crypt

CMD ["secrets-crypt"]
