FROM postgres:latest

ENV POSTGRES_DB=postgres
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=mypass

# This script will be executed during container startup
COPY create-table.sql /docker-entrypoint-initdb.d/
