apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: custom-wasm-middleware
spec:
  type: middleware.http.wasm
  version: v1
  metadata:
  - name: url
    value: "file://custom-go-middleware/main.wasm"
