apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: postgres-binding-counter
  namespace: default
spec:
  type: bindings.postgresql
  version: v1
  metadata:
  - name: connectionString
    value: "host=localhost user=postgres password=mypass port=5432 connect_timeout=10 database=postgres"
