apiVersion: apps/v1
kind: Deployment
metadata:
  name: secrets-crypt
  labels:
    app: secrets-crypt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secrets-crypt
  template:
    metadata:
      labels:
        app: secrets-crypt
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "secrets-crypt"
        dapr.io/app-port: "8080"
    spec:
      containers:
        - name: secrets-crypt
          image: leonardpahlke/secrets-crypt:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: secrets-crypt
spec:
  selector:
    app: secrets-crypt
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
