[package]
name = "dapr-pubsub-publisher"
version = "0.1.0"
edition = "2021"

[dependencies]
hyper = { version = "1", features = ["full"] }
tokio = { version = "1", features = ["full"]}
serde_json = "1.0"
reqwest = { version = "0.11", features = ["json"] }
